### ISSUE TITLE
Cannot Run scripts.opt_cam as cannot find head_model.obj

### ISSUE THREAD

**Issue by AumPatel2208** [GAP-LAB-CUHK-SZ/HairStep#13]
I cannot seem to find head_model.obj in the repository or the Google Drive. Where would this be located? or am I able to run without it.
```
CUDA_VISIBLE_DEVICES=0 python -m scripts.opt_cam
  0%|                                                                                                                                                                                                     | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/miniconda3/envs/hairstep/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/miniconda3/envs/hairstep/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/GitRepos/HairStep/scripts/opt_cam.py", line 63, in <module>
    opt_cam(sample)
  File "/home/GitRepos/HairStep/scripts/opt_cam.py", line 24, in opt_cam
    lmk_opt = OptLandmark(target_lmk, input_image).cuda()
  File "/home/GitRepos/HairStep/lib/util/opt_lmk.py", line 45, in __init__
    self.lmk_3D = self.load_lmk_3D()
  File "/home/GitRepos/HairStep/lib/util/opt_lmk.py", line 60, in load_lmk_3D
    vertices, _ = load_obj_mesh(self.head_obj_path)
  File "/home/GitRepos/HairStep/lib/mesh_util.py", line 114, in load_obj_mesh
    f = open(mesh_file, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/data2/paul/hair/Dataset/head_model.obj'
```

**Comment by PAULYZHENG** [comment]
Thanks for pointing out this bug. It has been fixed by this [commit](https://github.com/GAP-LAB-CUHK-SZ/HairStep/commit/3caedf5d3eebb9780ddf48fc3032dafefffdc0eb).
